<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BoardGames.Core\BoardGames.Core.csproj" />
    <ProjectReference Include="..\BoardGames.Gomoku\BoardGames.Gomoku.csproj" />
    <ProjectReference Include="..\BoardGames.Reversi\BoardGames.Reversi.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
